<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<CodeAnalysisRuleSet>../DFC.Digital.CodeAnalysis.ruleset</CodeAnalysisRuleSet>
		<PackageId>DFC.GeoCoding.Standard</PackageId>
		<Version>2.0.0</Version>
		<IsPackable>true</IsPackable>
		<Authors>Education and Skills Funding Agency Team</Authors>
		<PackageDescription>Geocoding client for retrieving longitude and latitude information based on postcodes.</PackageDescription>
		<PackageTags>Geocoding</PackageTags>
		<Copyright>Copyright (c) 2020 Education and Skills Funding Agency Team</Copyright>
		<Description>Geocoding client for that provides longitude and latitude information based on postcodes.</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

</Project>
