parameters:
  - name: PublishNugetPackage
    displayName: Publish Nuget Package?
    type: boolean
    default: false

variables:
  SolutionBaseName: 'DFC.GeoCoding.Standard'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

steps:
  - checkout: self
    clean: true
    fetchDepth: 0

  - template:  StepTemplates\SetBuildNumber.yml

  - template:  StepTemplates\SetDotNetVersion.yml
    parameters:
      DotNetVersion: 8.x

  - template:  StepTemplates\BuildTestPublishNuget.yml
    parameters:
      ProjectName: ${{ variables.SolutionBaseName }}
      PathToProjectFile: ${{ variables.SolutionBaseName }}\${{ variables.SolutionBaseName }}.csproj
      PublishNuget: ${{ parameters.PublishNugetPackage }}
      PackageFeedName: 'NationalCareersService'
