parameters:
  - name: PublishNugetPackage
    displayName: Publish Nuget Package?
    type: boolean
    default: false

variables:
  SolutionBaseName: 'DFC.GeoCoding.Standard'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

resources:
  repositories:
  - repository: Infra
    name: dfe-ncs-infrastructure
    type: git

steps:
  - checkout: self
    clean: true
    fetchDepth: 0
  - template:  AzureDevOps\StepTemplates\SetDotNetVersion.yml@Infra

  - template:  AzureDevOps\StepTemplates\SetDotNetVersion.yml@Infra
    parameters:
      DotNetVersion: 8.x

  - template:  AzureDevOps\StepTemplates\BuildTestPublishNuget.yml@Infra
    parameters:
      ProjectName: ${{ variables.SolutionBaseName }}
      PathToProjectFile: ${{ variables.SolutionBaseName }}\${{ variables.SolutionBaseName }}.csproj
      PublishNuget: ${{ parameters.PublishNugetPackage }}
      PackageFeedName: 'NationalCareersService'
